name: Package Mattermost Plugin

on:
  workflow_dispatch:

jobs:
  package:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Create plugin package
        run: |
          mkdir plugin
          cp -r plugin.json webapp .filestore plugin/
          tar -czf ir.elecserv.tar.gz -C plugin .

      - name: Upload package
        uses: actions/upload-artifact@v4
        with:
          name: mattermost-plugin
          path: ir.elecserv.tar.gz
